// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiGxIU2c4dcKR9BQFGWWy3uTZtFFMAvg',
    appId: '1:296546122915:android:2a633c7fe2131c68fb9316',
    messagingSenderId: '296546122915',
    projectId: 'grocery-st-33f86',
    storageBucket: 'grocery-st-33f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXqY2gNbCW9ukHF12s-RqS-3gOr-SVe88',
    appId: '1:296546122915:ios:2d2ff1cd62ac6e6afb9316',
    messagingSenderId: '296546122915',
    projectId: 'grocery-st-33f86',
    storageBucket: 'grocery-st-33f86.appspot.com',
    androidClientId: '296546122915-6689rq8rptj4fgvmhhmsp19uopt8ia4s.apps.googleusercontent.com',
    iosClientId: '296546122915-psqetr57444p6nemegb3stidob1sd6bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
